default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: test123
  host: localhost
  port: 5432

development:
  <<: *default
  database: rubyblog
  #database: gmr_staging1 
  #database: gmr_production
